# Generated by Django 6.0.6 on 2026-07-14 11:04

from django.db import migrations
from django.core.files.base import ContentFile
from django.utils.text import slugify
from urllib.request import urlopen, Request
import logging

logger = logging.getLogger(__name__)

def seed_menu_items_to_cloudinary(apps, schema_editor):
    Menu = apps.get_model('restaurant', 'Menu')
    
    default_items = [
        # Starters
        {
            "title": "Greek Salad", 
            "price": 12.99, 
            "inventory": 50,
            "source_url": "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800"
        },
        {
            "title": "Bruschetta", 
            "price": 8.99, 
            "inventory": 30,
            "source_url": "https://images.unsplash.com/photo-1572656631137-7935297eff55?w=800"
        },
        {
            "title": "Calamari Fritti", 
            "price": 14.50, 
            "inventory": 20,
            "source_url": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800"
        },
        
        # Mains
        {
            "title": "Grilled Fish", 
            "price": 20.00, 
            "inventory": 25,
            "source_url": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800"
        },
        {
            "title": "Lemon Chicken Pasta", 
            "price": 18.50, 
            "inventory": 35,
            "source_url": "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800"
        },
        {
            "title": "Ribeye Steak", 
            "price": 28.99, 
            "inventory": 15,
            "source_url": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800"
        },
        {
            "title": "Vegetarian Lasagna", 
            "price": 16.00, 
            "inventory": 22,
            "source_url": "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800"
        },
        
        # Desserts
        {
            "title": "Lemon Dessert", 
            "price": 6.50, 
            "inventory": 40,
            "source_url": "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800"
        },
        {
            "title": "Tiramisu", 
            "price": 7.50, 
            "inventory": 30,
            "source_url": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800"
        },
        
        # Drinks
        {
            "title": "Fresh Mint Limonana", 
            "price": 4.50, 
            "inventory": 100,
            "source_url": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800"
        },
    ]
    
    for item in default_items:
        # 1. Create or get the record (to avoid duplicates)
        menu_item, created = Menu.objects.get_or_create(
            title=item["title"],
            defaults={
                "price": item["price"], 
                "inventory": item["inventory"],
            }
        )
        
        # 2. If it was created (or doesn't have an image set yet), fetch the image
        # Match your exact Model image field name here (e.g., menu_item.image or menu_item.thumbnail)
        if created or not menu_item.image:
            try:
                logger.info(f"Downloading and uploading seed image for {item['title']} to Cloudinary...")
                
                # Use a user-agent header to avoid getting blocked by standard scraping blocks
                req = Request(
                    item["source_url"], 
                    headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
                )
                
                # Fetch image binary from the source
                with urlopen(req, timeout=15) as response:
                    image_data = response.read()
                
                # Convert binary to Django ContentFile
                file_name = f"{slugify(item['title'])}.jpg"
                django_file = ContentFile(image_data, name=file_name)
                
                # Save the file to your ImageField. 
                # This triggers the storage backend, sending the file straight to Cloudinary.
                menu_item.image.save(file_name, django_file, save=True)
                
            except Exception as e:
                logger.error(f"Failed to upload image for {item['title']}: {str(e)}")
                # We catch exceptions so that database migrations don't crash entirely 
                # if there is a temporary network hiccup or timeout.
                continue

def remove_menu_items(apps, schema_editor):
    Menu = apps.get_model('restaurant', 'Menu')
    titles = [item["title"] for item in Menu.objects.all()] # Or define your specific list
    # Deleting the record will clean up DB references. 
    # Note: Depending on Cloudinary settings, you may need to delete assets manually 
    # in the Cloudinary dashboard if you run a full migration roll-back.
    Menu.objects.filter(title__in=titles).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_image'), 
    ]
        

    operations = [
        migrations.RunPython(seed_menu_items_to_cloudinary, reverse_code=remove_menu_items),
    ]